[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cleaner"
version = "0.1.0"
dependencies = [
    "click==8.1.8",
]

[project.scripts]
cleaner = "cleaner.cli:main"